# -*- coding: utf-8 -*-
"""1_andares_hotel_sem_13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myb_2Fp8v9BEjz1P3aeJm-bWBRz9lrr8
"""

#Precisamos imprimir um número para cada andar de um hotel de 20 andares. Porém, o dono do hotel é supersticioso e optou por não ter um 13ro andar.
#Escreva um código que imprima todos os números exceto o número 13.
#Escreva mais dois códigos que resolvam o mesmo problema, mas dessa vez usando os outros dois tipos de laços de repetição aprendidos.
#Como desafio, imprima eles em ordem decrescente (20, 19, 18...)

print("Usando for:")
for andar in range(20, 0, -1):
    if andar != 13:
        print(andar)

print("\nUsando while:")
andar = 20
while andar > 0:
    if andar != 13:
        print(andar)
    andar -= 1

print("\nSimulando do-while:")
andar = 20
while True:
    if andar != 13:
        print(andar)
    andar -= 1
    if andar <= 0:
        break

