# -*- coding: utf-8 -*-
"""3_calculadora_interativa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJXO7G_d8GBEQp1exqUAiY3n_omohwKI
"""

#Faça uma função calculadora que os números e as operações serão feitas pelo usuário. O código deve ficar rodando infinitamente até que o usuário escolha a opção de sair. No início, o programa mostrará a seguinte lista de operações:
#1: Soma
#2: Subtração
#3: Multiplicação
#4: Divisão
#0: Sair
#Digite o número para a operação correspondente e caso o usuário introduza qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” e voltar ao menu de opções.
#Após a seleção, o sistema deve pedir para o usuário inserir o primeiro e segundo valor, um de cada. Depois precisa executar a operação e mostrar o resultado na tela. Quando o usuário escolher a opção “Sair”, o sistema irá parar.
#É necessário que o sistema mostre as opções sempre que finalizar uma operação e mostrar o resultado.

def calculadora():
    while True:
        print("\nEscolha uma operação:")
        print("1: Soma")
        print("2: Subtração")
        print("3: Multiplicação")
        print("4: Divisão")
        print("0: Sair")

        opcao = input("Digite o número para a operação correspondente: ")

        if opcao == '0':
            print("Saindo...")
            break
        elif opcao not in ['1', '2', '3', '4']:
            print("Essa opção não existe.")
            continue

        try:
            primeiro_valor = float(input("Digite o primeiro valor: "))
            segundo_valor = float(input("Digite o segundo valor: "))
        except ValueError:
            print("Por favor, insira números válidos.")
            continue

        if opcao == '1':
            resultado = primeiro_valor + segundo_valor
            operacao = "Soma"
        elif opcao == '2':
            resultado = primeiro_valor - segundo_valor
            operacao = "Subtração"
        elif opcao == '3':
            resultado = primeiro_valor * segundo_valor
            operacao = "Multiplicação"
        elif opcao == '4':
            if segundo_valor == 0:
                print("Erro: Divisão por zero não é permitida.")
                continue
            resultado = primeiro_valor / segundo_valor
            operacao = "Divisão"

        print(f"O resultado da {operacao} entre {primeiro_valor} e {segundo_valor} é: {resultado}")

calculadora()