# -*- coding: utf-8 -*-
"""4_calculadora_idade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIWT4xGFF0ZKRPuu2qwoWQhAwWvfwH2U
"""

#Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
#A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).
#Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.

def calcular_idade():
    from datetime import datetime

    ano_atual = 2022
    nome_completo = input("Digite seu nome completo: ")

    while True:
        try:
            ano_nascimento = int(input("Digite seu ano de nascimento (entre 1922 e 2021): "))
            if 1922 <= ano_nascimento <= 2021:
                break
            else:
                print("Ano inválido. Por favor, digite um ano entre 1922 e 2021.")
        except ValueError:
            print("Entrada inválida. Por favor, insira um número válido para o ano.")

    idade = ano_atual - ano_nascimento
    print(f"{nome_completo}, você completou ou completará {idade} anos em {ano_atual}.")

calcular_idade()